/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

int main(void)
{
    uint32_t *RCC_APB2ENR   = (uint32_t*)0x40021018;   //APB2 RCC-CLOCK ENABLE REGISTER ADDRESS
    *RCC_APB2ENR |= 0x00000004;    //ENABLING GPIO-A CLOCK

    uint32_t *GPIOA_CRL = (uint32_t*)0x40010800;
    *GPIOA_CRL &= 0xfffffff0;
    *GPIOA_CRL |= 0x00000002;

    uint32_t *GPIOA_ODR = (uint32_t*)0x4001080C;
    while(1)
    {
    *GPIOA_ODR = 0x00000000;
    for(int32_t i=0;i<40000;i++);
    *GPIOA_ODR = 0x00000001;
    for(int32_t i=0;i<40000;i++);
    }


}

